name: Everything
main: org.ultragore.everything.Everything
version: 0.1
depend: [WorldGuard, WorldEdit, ChestCommands, AuthMe, Vault, LuckPerms, Multiverse-Core, ProtocolLib, MurderMystery]
api-version: 1.16
commands:
   opregions:
      description: Reloads config
      usage: /opregions reload
   everything:
      description: Main Everything plugin command
      usage: /everything help
   cce:
      description: Loads module menus and dumps them
      usage: /cce refresh [menu_file_name]
   anticmd:
      usage: /anticmd reload
   casino:
      usage: /casino reload
   wee:
      usage: /wee reload
   torch:
      usage: |
         Torch commands usage
         /torch reload
         /torch give <nickname> <label> [amount]
         /torch list
   mlobby:
      usage: |
         MinigamesLobby commands usage
         /mlobby reload
         /mlobby join <lobby_world>
         /mlobby leave