#Usable item map description:
# name: '...'       #required
# material: MAT     #required
# enchanted: bool   #required
# milk_cancel: bool #required
# lore: ['...']
# use_message: '...'
# cooldown: 123sec
# use_particles:  ['particle,offsetX,offsetY,offsetZ,count']
# potion_effects: ['<effect>,<duration>[,amplifier[,chance]]']
# food_level_up: 123  # 1 level is a half of food icon
# potion_color: 'R G B' # 0-255 0-255 0-255
# add_potion_effects: bool # default: true. If true and material is POTION then
#                          # potion_effects will be added to ItemStack, and only
#                          # random potion effects will be applied on use.
#
#Permissions;
# everything.torch.consume - allows to use usable items.
# everything.torch.give - access to /torch give command
# everything.torch.reload - access to /torch reload command
# everything.torch.list - access to /torch list command

usable_items:
   shpak:
      name: 'Ереванский шпак'
      lore:
      - 'Стоит 5к баксов'
      - 'Ща с молым его въ**али'
      - 'Ах***о вставляет бл* буду'
      material: NETHERITE_SCRAP
      use_message: 'Вы закинули ереванский шпак'
      cooldown: 10
      enchanted: false
      milk_cancel: true
      use_particles:
      - 'CRIT,0,1,0,5'
      potion_effects:
      - 'JUMP,50,2'
      - 'POISON,20,2,50'

group_cooldowns:
   drugs: ['shpak']

messages:
   permission_denied: '§cYou have no permissions to use this item.'
   default_use_message: 'You have consumed {name}.'
   cooldown: 'Wait {left}sec to use this item.'