default_cancel_message: '&cКоманда не найдена.'

excluded_commands:
- cmd: //sphere
  cancel_message: 'sieg heil'
  issue_instead_command: 'help'

# anticmd.bypass
# anticmd.reload
#
# cancel_message and issue_instead_command are not required.
# cancel_message can be set to NONE
#
# if cmd starts with '^' then user command will be checked, if it starts with
# cmd value. Otherwise user command will be checked on equals.