group_restrictions:
   admin:
      blocks_change_limit: 500
      issue_cooldown: 20
      edit_others_regions: false
      edit_world: true
   moder:
      blocks_change_limit: 100
      issue_cooldown: 20
      edit_others_regions: false
      edit_world: false

default_restrictions:
   blocks_change_limit: 50
   issue_cooldown: 20
   edit_others_regions: false
   edit_world: false

messages:
   blocks_limit: "§dYou've reached blocks limit {LIMIT}, trying to change {AFFECTED} blocks."
   edit_other_region: "§dYou're not allowed to edit others regions."
   edit_world: "§dYou're not allowed to edit outside of regions."
   now_allowed_arguments: "§dThese arguments are forbidden for this command: {ARGUMENTS}"
   under_cooldown: "§dWait {SECONDS}s for the next commdnd issue."